dist: trusty

language: bash

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y build-essential curl git
  - curl -O https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
  - bash Miniconda3-latest-Linux-x86_64.sh -b 

script:
  - bash bin/install/conda_env.sh
  - source activate smsk
  - snakemake 
