#!/usr/bin/env bash

set -euo pipefail

# pre-commit hooks:
# check that the pipeline works,
# check linters:
#   python conde: flake8
#   shell: shellcheck
#   yaml: yamllint
#   r: lintr

do_pipeline() {
    snakemake clean
    snakemake --use-conda -j
}

do_flake8() {
    flake8 \
        --ignore=E999 \
        Snakefile \
        "$(find src/ -name "*.py" -type f)"
}

do_shellcheck(){
    shellcheck \
        src/pre-commit \
        "$(find src/ -name "*.sh" -type f)"
}

do_yamllint(){
    yamllint \
        --strict \
        ./*.yml

    find src/ -name '*.yml' -o -name '*.yaml' -type f -exec yamllint --strict {} \;
}

fail () {
    echo "$0: [FAILED]"
    exit 1
}

if git rev-parse --verify HEAD >/dev/null 2>&1
then
        against=HEAD
else
        # Initial commit: diff against an empty tree object
        against=4b825dc642cb6eb9a060e54bf8d69288fbee4904
fi

echo "Running the pipeline"
do_pipeline || fail Snakemake

echo "Linting Snakefiles"
do_flake8 || fail flake8

echo "Linting Shell scripts"
do_shellcheck || fail shellcheck

echo "Linting YAML files"
do_yamllint || fail yamllint

# If there are whitespace errors, print the offending file names and fail.
exec git diff-index --check --cached $against --
